clusterName: "opensearch-cluster"
replicas: 1
singleNode: true

service:
  type: NodePort
  port: 9200
  nodePort: 30920

config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    discovery.type: single-node
    # disable ml sync job spam in logs
    plugins.ml_commons.sync_up_job_interval_in_seconds: 0

# Disable security for development 
securityConfig:
  enabled: true
  createDemoConfig: false

  plugins.security.ssl.transport.pemcert_filepath: certs/tls.crt
  plugins.security.ssl.transport.pemkey_filepath: certs/tls.key
  plugins.security.ssl.transport.pemtrustedcas_filepath: certs/ca.crt
  plugins.security.ssl.transport.enforce_hostname_verification: false
  plugins.security.ssl.http.enabled: true
  plugins.security.ssl.http.pemcert_filepath: certs/tls.crt
  plugins.security.ssl.http.pemkey_filepath: certs/tls.key
  plugins.security.ssl.http.pemtrustedcas_filepath: certs/ca.crt
  plugins.security.allow_unsafe_democertificates: false
  plugins.security.allow_default_init_securityindex: true
  plugins.security.authcz.admin_dn:
    - CN=opensearch-cluster-master,O=opensearch,L=opensearch,C=US
  plugins.security.audit.type: internal_opensearch
  plugins.security.enable_snapshot_restore_privilege: true
  plugins.security.check_snapshot_restore_write_privileges: true
  plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
  plugins.security.system_indices.enabled: true
  plugins.security.system_indices.indices:
    - ".opendistro-alerting-config"
    - ".opendistro-alerting-alert*"
    - ".opendistro-anomaly-results*"
    - ".opendistro-anomaly-detector*"
    - ".opendistro-anomaly-checkpoints"
    - ".opendistro-anomaly-detection-state"
    - ".opendistro-reports-*"
    - ".opendistro-notifications-*"
    - ".opendistro-notebooks"
    - ".opendistro-asynchronous-search-response*"

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

persistence:
  enabled: true
  storageClass: "openebs-cstor"
  size: 10Gi

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xms256m -Xmx512m"
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-admin-secret
        key: OPENSEARCH_INITIAL_ADMIN_PASSWORD

extraVolumes:
  - name: opensearch-certs
    secret:
      secretName: opensearch-certs

extraVolumeMounts:
  - name: opensearch-certs
    mountPath: /usr/share/opensearch/config/certs
    readOnly: true


