clusterName: "opensearch-cluster"
replicas: 1
singleNode: true

service:
  type: NodePort
  port: 9200
  nodePort: 30920

config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    discovery.type: single-node
    # disable ml sync job spam in logs
    plugins.ml_commons.sync_up_job_interval_in_seconds: 0
    
    # Custom SSL Transport configuration  
    plugins.security.ssl.transport.pemcert_filepath: /usr/share/opensearch/config/certs/tls.crt
    plugins.security.ssl.transport.pemkey_filepath: /usr/share/opensearch/config/certs/tls.key
    plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/opensearch/config/certs/ca.crt
    plugins.security.ssl.transport.enforce_hostname_verification: false
    
    # Custom SSL HTTP configuration
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: /usr/share/opensearch/config/certs/tls.crt
    plugins.security.ssl.http.pemkey_filepath: /usr/share/opensearch/config/certs/tls.key
    plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/opensearch/config/certs/ca.crt


# Disable test certs
securityConfig:
  enabled: false

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 10Gi

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xms256m -Xmx512m"
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-admin-secret
        key: OPENSEARCH_INITIAL_ADMIN_PASSWORD

extraVolumes:
  - name: opensearch-certs
    secret:
      secretName: opensearch-certs

extraVolumeMounts:
  - name: opensearch-certs
    mountPath: /usr/share/opensearch/config/certs
    readOnly: true
