clusterName: "opensearch-cluster"
replicas: 1

service:
  type: ClusterIP
  port: 9200
  headless:
    annotations: {}



# Disable test certs
securityConfig:
  enabled: false

resources:
  requests:
    cpu: "200m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 10Gi

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xms1g -Xmx1g"
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-admin-secret
        key: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        
  # Custom SSL Transport configuration
  - name: plugins.security.ssl.transport.pemcert_filepath
    value: "/usr/share/opensearch/config/certs/tls.crt"
  - name: plugins.security.ssl.transport.pemkey_filepath
    value: "/usr/share/opensearch/config/certs/tls.key"
  - name: plugins.security.ssl.transport.pemtrustedcas_filepath
    value: "/usr/share/opensearch/config/certs/ca.crt"

  # Custom SSL HTTP configuration
  - name: plugins.security.ssl.http.enabled
    value: "true"
  - name: plugins.security.ssl.http.pemcert_filepath
    value: "/usr/share/opensearch/config/certs/tls.crt"
  - name: plugins.security.ssl.http.pemkey_filepath
    value: "/usr/share/opensearch/config/certs/tls.key"
  - name: plugins.security.ssl.http.pemtrustedcas_filepath
    value: "/usr/share/opensearch/config/certs/ca.crt"

extraVolumes:
  - name: opensearch-nodes-cert
    secret:
      secretName: opensearch-nodes-cert
extraVolumeMounts:
  - name: opensearch-nodes-cert
    mountPath: /usr/share/opensearch/config/certs
    readOnly: true
