clusterName: "opensearch-cluster"
replicas: 3

service:
  type: ClusterIP
  port: 9200
  headless:
    annotations: {}



# Disable test certs
securityConfig:
  enabled: false

resources:
  requests:
    cpu: "200m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 10Gi

extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xms1g -Xmx1g"
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-admin-secret
        key: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        
  # Custom SSL Transport configuration
  - name: plugins.security.ssl.transport.pemcert_filepath
    value: "/usr/share/opensearch/config/certs/tls.crt"
  - name: plugins.security.ssl.transport.pemkey_filepath
    value: "/usr/share/opensearch/config/certs/tls.key"
  - name: plugins.security.ssl.transport.pemtrustedcas_filepath
    value: "/usr/share/opensearch/config/certs/ca.crt"

  # Custom SSL HTTP configuration
  - name: plugins.security.ssl.http.enabled
    value: "true"
  - name: plugins.security.ssl.http.pemcert_filepath
    value: "/usr/share/opensearch/config/certs/tls.crt"
  - name: plugins.security.ssl.http.pemkey_filepath
    value: "/usr/share/opensearch/config/certs/tls.key"
  - name: plugins.security.ssl.http.pemtrustedcas_filepath
    value: "/usr/share/opensearch/config/certs/ca.crt"
  # Cluster configuration for multiple nodes
  - name: "cluster.name"
    value: "opensearch-cluster"
  - name: "network.host"
    value: "0.0.0.0"
  - name: "node.name"
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: "discovery.seed_hosts"
    value: "opensearch-cluster-master-headless"
  - name: "cluster.initial_master_nodes"
    value: "opensearch-cluster-master-0,opensearch-cluster-master-1,opensearch-cluster-master-2"
  
  # Bootstrap settings for multi-node cluster
  - name: "bootstrap.memory_lock"
    value: "false"
  
  # Network and transport settings
  - name: "network.bind_host"
    value: "0.0.0.0"
  - name: "network.publish_host"
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: "transport.host"
    value: "0.0.0.0"
  - name: "transport.bind_host"
    value: "0.0.0.0"
  
  # Security settings for node communication
  - name: plugins.security.nodes_dn
    value: "CN=*.opensearch.svc.cluster.local"
  - name: plugins.security.allow_default_init_securityindex
    value: "true"
  
extraVolumes:
  - name: opensearch-nodes-cert
    secret:
      secretName: opensearch-nodes-cert
extraVolumeMounts:
  - name: opensearch-nodes-cert
    mountPath: /usr/share/opensearch/config/certs
    readOnly: true


ingress:
  enabled: true
  ingressClassName: nginx  
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  path: /
  hosts:
    - api.opensearch.gruzo.kz  
  tls:
    - secretName: os-gruzo-kz-tls
      hosts:
        - api.opensearch.gruzo.kz