# for templating domains in values
environments:
  default:
    values:
      - values/domains.yaml

---

repositories:
  - name: opensearch
    url: https://opensearch-project.github.io/helm-charts
  - name: longhorn
    url: https://charts.longhorn.io
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: prometheus-community 
    url: https://prometheus-community.github.io/helm-charts
 

hooks:
  - events: ["prepare"]
    showlogs: true
    command: bash
    args:
      - -c
      - |
        if ! kubectl -n opensearch get secret opensearch-admin-secret >/dev/null 2>&1; then
          echo "Missing secret: opensearch-admin-secret" >&2
          exit 1
        fi

  - events: ["prepare"]
    showlogs: true
    command: bash
    args:
      - -c
      - |
        if ! kubectl -n longhorn-system get secret longhorn-ui-password -o jsonpath="{.data.auth}" >/dev/null 2>&1; then
          echo "Secret longhorn-ui-password doesn't exists or not populated" >&2
          exit 1
        fi

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.13.3
    createNamespace: true
    values:
      - installCRDs: true

  - name: opensearch-certs
    namespace: opensearch
    chart: ./charts/opensearch-certs
    createNamespace: true
    needs:
      - cert-manager/cert-manager
    values:
      - values/domains.yaml

  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    createNamespace: true
    values:
      - values/longhorn-values.yaml.gotmpl
    
  - name: opensearch
    namespace: opensearch
    chart: opensearch/opensearch
    needs:
    - opensearch/opensearch-certs
    values:
      - values/opensearch-values.yaml.gotmpl

  - name: opensearch-dashboards
    namespace: opensearch
    chart: opensearch/opensearch-dashboards
    values:
      - values/dashboard-values.yaml.gotmpl

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx 
    values:
      - values/ingress-nginx-values.yaml


  # - name: kube-prometheus-stack
  #   namespace: prometheus
  #   createNamespace: true
  #   chart: prometheus-community/kube-prometheus-stack
  #   values:
  #     - values/prometheus-stack-values.yaml
