repositories:
  - name: opensearch
    url: https://opensearch-project.github.io/helm-charts

releases:
  - name: opensearch
    namespace: opensearch
    chart: opensearch/opensearch
    values:
      - values/opensearch-values.yaml

  - name: opensearch-dashboards
    namespace: opensearch
    chart: opensearch/opensearch-dashboards
    values:
      - values/dashboard-values.yaml