repositories:
  - name: opensearch
    url: https://opensearch-project.github.io/helm-charts
  - name: longhorn
    url: https://charts.longhorn.io

releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    createNamespace: true

    values:
      - defaultSettings:
          defaultReplicaCount: 2  
          defaultDataPath: /var/lib/longhorn  
          defaultLonghornStaticStorageClass: longhorn
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
  
  - name: opensearch
    namespace: opensearch
    chart: opensearch/opensearch
    values:
      - values/opensearch-values.yaml

  - name: opensearch-dashboards
    namespace: opensearch
    chart: opensearch/opensearch-dashboards
    values:
      - values/dashboard-values.yaml