---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
data:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: Aizuku5uf5aenoo2ulee

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:3.1.0
          env:
              - name: discovery.type
                value: "single-node"
              - name: cluster.name
                value: "dev-cluster"
              - name: node.name
                value: "opensearch-dev"
              - name: bootstrap.memory_lock
                value: "true"
              - name: network.host
                value: "0.0.0.0"
              - name: OPENSEARCH_JAVA_OPTS
                value: "-Xms512m -Xmx512m"
              - name: DISABLE_SECURITY_PLUGIN
                value: "true"
          envFrom:
            - configMapRef:
                name: opensearch-config
          ports:
            - containerPort: 9200
          volumeMounts:
            - mountPath: /usr/share/opensearch/data
              name: data
          resources:
            requests:
              cpu: "300m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "1.5Gi"
      volumes:
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30920
  selector:
    app: opensearch

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboards
  template:
    metadata:
      labels:
        app: dashboards
    spec:
      containers:
        - name: dashboards
          image: opensearchproject/opensearch-dashboards:3.1.0
          env:
            - name: OPENSEARCH_HOSTS
              value: '["http://opensearch:9200"]'
            - name: OPENSEARCH_USERNAME
              value: "admin"
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: opensearch-config
                  key: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          ports:
            - containerPort: 5601
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "4Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: dashboards
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30561
  selector:
    app: dashboards
