---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: opensearch-dashboards
  name: opensearch-dashboards
spec:
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
  selector:
    io.kompose.service: opensearch-dashboards

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: opensearch-node1
  name: opensearch-node1
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9600"
      port: 9600
      targetPort: 9600
  selector:
    io.kompose.service: opensearch-node1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: opensearch-dashboards
  name: opensearch-dashboards
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opensearch-dashboards
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: opensearch-dashboards
    spec:
      containers:
        - env:
            - name: OPENSEARCH_HOSTS
              value: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
          envFrom:
            - configMapRef:
                name: env
          image: opensearchproject/opensearch-dashboards:latest
          name: opensearch-dashboards
          ports:
            - containerPort: 5601
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
data:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: Aizuku5uf5aenoo2ulee
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: opensearch-dashboards-env
  name: env

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: opensearch-node1
  name: opensearch-node1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opensearch-node1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: opensearch-node1
    spec:
      containers:
        - env:
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms1024m -Xmx1024m
            - name: cluster.initial_cluster_manager_nodes
              value: opensearch-node1,opensearch-node2
            - name: cluster.name
              value: opensearch-cluster
            - name: discovery.seed_hosts
              value: opensearch-node1,opensearch-node2
            - name: node.name
              value: opensearch-node1
          envFrom:
            - configMapRef:
                name: env
          image: opensearchproject/opensearch:latest
          name: opensearch-node1
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9600
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/opensearch/data
              name: opensearch-data1
      restartPolicy: Always
      volumes:
        - name: opensearch-data1
          persistentVolumeClaim:
            claimName: opensearch-data1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: opensearch-data1
  name: opensearch-data1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: opensearch-node2
  name: opensearch-node2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opensearch-node2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml -o kubernetes.yml convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: opensearch-node2
    spec:
      containers:
        - env:
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms1024m -Xmx1024m
            - name: cluster.initial_cluster_manager_nodes
              value: opensearch-node1,opensearch-node2
            - name: cluster.name
              value: opensearch-cluster
            - name: discovery.seed_hosts
              value: opensearch-node1,opensearch-node2
            - name: node.name
              value: opensearch-node2
          envFrom:
            - configMapRef:
                name: env
          image: opensearchproject/opensearch:latest
          name: opensearch-node2
          volumeMounts:
            - mountPath: /usr/share/opensearch/data
              name: opensearch-data2
      restartPolicy: Always
      volumes:
        - name: opensearch-data2
          persistentVolumeClaim:
            claimName: opensearch-data2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: opensearch-data2
  name: opensearch-data2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path

