apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: os-gruzo-kz-cert
  namespace: opensearch
spec:
  secretName: os-gruzo-kz-tls
  issuerRef:       
    #le-stag  for testing      
    name: le-prod
    kind: Issuer
  dnsNames:
    - os.gruzo.kz
    - opensearch.gruzo.kz