# OpenSearch Configuration for k0s cluster
clusterName: "opensearch-cluster"
replicas: 1
# NodePort service configuration
service:
  type: NodePort
  port: 9200
  nodePort: 30920

# OpenSearch configuration
config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    plugins.security.disabled: true
    discovery.type: single-node

# Disable security for development
securityConfig:
  enabled: false

# Resource allocation for self-hosted environment
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

# Persistent storage
persistence:
  enabled: true
  size: 10Gi
  storageClass: "openebs-hostpath"
# JVM heap settings and admin password
extraEnvs:
  - name: OPENSEARCH_JAVA_OPTS
    value: "-Xms256m -Xmx512m"
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "Aizuku5uf5aenoo2ulee"
  - name: cluster.initial_master_nodes
    value: null
